# Additional Properties Passed to Actuator      
info:
  app: 
    name: Sitatex Online - Discovery Service
    description: This is a discovery service for Sitatex Online 

# Actuator Management Properties
management:
  endpoint:
    shutdown:
      enabled: true
    metrics:
      enabled: true  
   
# Discovery Config For Atlanta Nodes
spring:
  profiles: STXOL-ATL-01
server:
  port: 8761
eureka:
    instance:
        environment: Development
        datacenter: ATLANTA
        data-center-info: SITA-ATL-EAST
        hostname: localhost
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
        metadataMap:
          zone: ATL-EAST
    client:
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0 
        enableSelfPreservation: false  # Remove this in Prod        
        evictionIntervalTimerInMs: 3000
        
