# Additional Properties Passed to Actuator      
info:
  app: 
    name: Sitatex Online - Discovery Service
    description: This is a discovery service for Sitatex Online 

# Actuator Management Properties
management:
  endpoint:
    shutdown:
      enabled: true
    metrics:
      enabled: true     
    refresh:
      enabled: false
 

# Discovery Config For Atlanta Nodes
spring:
  profiles: STXOL-DISCOVERY-ATL-01
server:
  port: 8761
eureka:
  instance:
    instanceId: STXOL-DISCOVERY-ATL-01
    hostname: localhost     
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      zone: ATL-EAST
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      shouldDisableDelta: true
  server:
    waitTimeInMsWhenSyncEmpty: 0 
    enableSelfPreservation: false  # Remove this in Prod        
    evictionIntervalTimerInMs: 3000

---
spring:
  profiles: STXOL-DISCOVERY-ATL-02
server:
  port: 8762
eureka:
  instance:
    instanceId: STXOL-DISCOVERY-ATL-02
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      zone: ATL-EAST
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      shouldDisableDelta: true
  server:
    waitTimeInMsWhenSyncEmpty: 0 
    enableSelfPreservation: false  # Remove this in Prod        
    evictionIntervalTimerInMs: 3000        
    