
# Common Configuration
ribbon:
  eureka:
    enabled: true
       
# Gateway Routing    
zuul:
  prefix: /api
  routes:
    client: 
      path: /client/**
      serviceId: client-service        


--- # STXOL-GATEWAY-ATL-01
spring:
  profiles: STXOL-GATEWAY-ATL-01
server:  
  port: 8765  
rabbitmq:
    host: 57.4.3.26
    port: 5672
    username: guest
    password: guest    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
    registerWithEureka: true
    preferSameZoneEureka: true
    shouldDisableDelta: true
  instance:
    instanceId: STXOL-GATEWAY-ATL-01
    preferIpAddress: false
    metadataMap:
      zone: ATL-EAST

  
--- # STXOL-GATEWAY-ATL-02
spring:
  profiles: STXOL-GATEWAY-ATL-02
server:  
  port: 8766
rabbitmq:
    host: 57.4.3.26
    port: 5672
    username: guest
    password: guest  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/, http://localhost:8761/eureka/
    registerWithEureka: true
    preferSameZoneEureka: true
    shouldDisableDelta: true
  instance:
    instanceId: STXOL-GATEWAY-ATL-02
    metadataMap:
      zone: ATL-EAST
     
