
# Common Configuration
zuul:
  prefix: /api
  routes:
    client: 
      path: /client/**
      serviceId: client-service        

ribbon:
  eureka:
    enabled: true

server:  
  port: ${PORT:8765}

# Gateway Config For Atlanta Nodes
spring:
  profiles: STXOL-GATEWAY-ATL-01
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    preferSameZoneEureka: true
    shouldDisableDelta: true
  instance:
    instanceId: STXOL-GATEWAY-ATL-01
    metadataMap:
      zone: ATL-EAST

