zuul:
  prefix: /api
  routes:
    client: 
      path: /client/**
      serviceId: client-service        

ribbon:
  eureka:
    enabled: true

---
spring:
  profiles: STXOL-ATL-01
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    preferSameZoneEureka: true
  instance:
    metadataMap:
      zone: ATL-EAST
server:  
  port: ${PORT:8765}
